Fix typo for the challenge Backwards
BishopFox/cloudfoxable pull request #18
Opened 2024-04-17 08:27 UTC by LuD1161

This PR fixes the typo in the challenge [backwards](https://cloudfoxable.bishopfox.com/challenges#Backwards-9), where `aws` is missed in the commands given in hints section.

Fixes - #17

2024-05-07 09:21 UTC, dbravo-bishopfox requested changes
Please remove this one extra 'aws'

2024-05-07 09:21 UTC, dbravo-bishopfox commented on aws/challenges/Backwards/challenge.yml
> +  `cloudfox aws -p cloudfoxable aws permissions -v2 | grep -i secret`
Thanks for contributing! Did you mean to insert this 'aws' here? I think this one is not necessary.

2024-05-07 10:04 UTC, LuD1161 commented
Sure I'll do that. Perhaps it was a typo 😅

On Tue, 7 May, 2024, 14:52 David, ***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Please remove this one extra 'aws'
> ------------------------------
>
> In aws/challenges/Backwards/challenge.yml
> <https://github.com/BishopFox/cloudfoxable/pull/18#discussion_r1592103867>
> :
>
> > @@ -35,7 +35,7 @@ hints:
>  - |-
>    If your stuck, try running the permissions command in cloudfox and grepping for the word secret:
>
> -  `cloudfox aws -p cloudfoxable permissions -v2 | grep -i secret`
> +  `cloudfox aws -p cloudfoxable aws permissions -v2 | grep -i secret`
>
> Thanks for contributing! Did you mean to insert this 'aws' here? I think
> this one is not necessary.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/BishopFox/cloudfoxable/pull/18#pullrequestreview-2042567024>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AEIITPXYFXMDNCXIR7QM7CTZBCMMBAVCNFSM6AAAAABGK2NYQCVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANBSGU3DOMBSGQ>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2024-05-08 09:26 UTC, LuD1161 commented
Fixed.

2024-05-08 16:08 UTC, dbravo-bishopfox approved these changes

2024-05-13 17:36 UTC, merged